services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=demo_db'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER=demo_user'
    ports:
      - '3306:3306'
