server:
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:3306/demo_db
    username: demo_user
    password: p@ssword
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 